-- Update handle_new_user function to autogenerate username on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  base_username TEXT;
  final_username TEXT;
  username_suffix INTEGER := 1;
BEGIN
  -- Generate base username from display name or email
  base_username := LOWER(
    REGEXP_REPLACE(
      COALESCE(NEW.raw_user_meta_data->>'display_name', SPLIT_PART(NEW.email, '@', 1)),
      '[^a-zA-Z0-9]',
      '',
      'g'
    )
  );
  
  -- Ensure minimum length
  IF LENGTH(base_username) < 3 THEN
    base_username := 'user' || SUBSTR(NEW.id::text, 1, 8);
  END IF;
  
  -- Find available username by adding suffix if needed
  final_username := base_username;
  WHILE EXISTS (SELECT 1 FROM profiles WHERE username = final_username) LOOP
    final_username := base_username || '_' || username_suffix;
    username_suffix := username_suffix + 1;
  END LOOP;
  
  -- Insert profile with autogenerated username
  INSERT INTO public.profiles (user_id, display_name, role, username, username_changed)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.email),
    COALESCE((NEW.raw_user_meta_data->>'role')::user_role, 'musiker'),
    final_username,
    FALSE
  );
  
  RETURN NEW;
END;
$function$;