// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkcdyqghfqyrlwjcsrnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrY2R5cWdoZnF5cmx3amNzcm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzAxNzcsImV4cCI6MjA3MTMwNjE3N30.zvNq7yhyyMMmbLE9trLxvCqd5HNoJ9JjokHOWGAJwWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'x-application-name': 'giggen-app'
    }
  },
  realtime: {
    reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 30000)
  }
});